import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Provider } from "@/components/ui/provider"



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Read Receipts',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/book.png',
        href: '/book.png'
      }
    ]
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
